apiVersion: v1
kind: Service
metadata:
  name: transact-api-r23
spec:
  type: NodePort
  ports:
    - port: 8080 #Service Port
      protocol: TCP
      targetPort: 8080 #Container Port
      nodePort: 30070 #Node Port
  selector:
    app: transact-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: transact-api
spec:
   replicas: 1 #Number of replicas
   selector:
     matchLabels:
       app: transact-api
   template:
     metadata:
       labels:
         app: transact-api

     spec:
         containers:
         - name: transact-api
           image: tlctraining.azurecr.io/transact-api:R23.7
           imagePullPolicy: IfNotPresent
           
           resources:
             requests:
               cpu: 1
               memory: 2G
             limits:
               cpu: 1
               memory: 5G
               
           ports:
             - name: api
               protocol: TCP
               containerPort: 8080

           env:
             - name: JMS_URL
               valueFrom:
                  configMapKeyRef:
                    name: r23-jms-config
                    key: url
             - name: JMS_VPN
               valueFrom:
                  configMapKeyRef:
                    name: r23-jms-config
                    key: vpn
             - name: JMS_USER
               valueFrom:
                  configMapKeyRef:
                    name: r23-jms-config
                    key: user
             - name: JMS_PASSWORD
               valueFrom:
                  secretKeyRef:
                    name: externals
                    key: JMS_PASSWORD
             - name: APP_USER
               valueFrom:
                  configMapKeyRef:
                    name: r23-db-config
                    key: appuser
             - name: APP_PASSWORD
               valueFrom:
                  secretKeyRef:
                    name: externals
                    key: APP_PWD
