apiVersion: v1
kind: Service
metadata:
  name: transact-web-r23
spec:
  type: NodePort
  ports:
    - port: 8080 #Service Port
      protocol: TCP
      targetPort: 8080 #Container Port
      nodePort: 30080 #Node Port
  selector:
    app: transact-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: transact-web
spec:
   replicas: 1 #Number of replicas
   selector:
     matchLabels:
       app: transact-web
   template:
     metadata:
       labels:
         app: transact-web

     spec:
         containers:
         - name: transact-web
           image: tlctraining.azurecr.io/transact-webk8s:R23.7
           imagePullPolicy: IfNotPresent
           
           resources:
             requests:
               cpu: 1
               memory: 2G
             limits:
               cpu: 1
               memory: 5G
               
           ports:
             - name: web
               protocol: TCP
               containerPort: 8080

           env:
             - name: JMS_URL
               valueFrom:
                  configMapKeyRef:
                    name: r23-jms-config
                    key: url
             - name: JMS_VPN
               valueFrom:
                  configMapKeyRef:
                    name: r23-jms-config
                    key: vpn
             - name: JMS_USER
               valueFrom:
                  configMapKeyRef:
                    name: r23-jms-config
                    key: user
             - name: JMS_PASSWORD
               valueFrom:
                  secretKeyRef:
                    name: externals
                    key: JMS_PASSWORD
             - name: OLTP_ACTIVE
               valueFrom:
                  configMapKeyRef:
                    name: r23-jms-config
                    key: oltp_active
             - name: SERVICE_ACTIVE
               valueFrom:
                  configMapKeyRef:
                    name: r23-jms-config
                    key: service_active
             - name: APP_USER
               valueFrom:
                  configMapKeyRef:
                    name: r23-db-config
                    key: appuser
             - name: APP_PASSWORD
               valueFrom:
                  secretKeyRef:
                    name: externals
                    key: APP_PWD
             - name: MAX_THREAD_COUNT
               valueFrom:
                  configMapKeyRef:
                    name: r23-db-config
                    key: max_thread_count
             - name: MDB_POOL_MAX
               valueFrom:
                  configMapKeyRef:
                    name: r23-db-config
                    key: mdb_pool_max
             - name: MAX_POOL_SIZE
               valueFrom:
                  configMapKeyRef:
                    name: r23-db-config
                    key: max_pool_size
             - name: OFS_QUEUE
               valueFrom:
                  configMapKeyRef:
                    name: r23-db-config
                    key: ofs_queue
             - name: OFSREPLY_QUEUE
               valueFrom:
                  configMapKeyRef:
                    name: r23-db-config
                    key: ofsreply_queue
